module.exports = {
  User: require('./User'),
  Destination: require('./Destination'),
  TourPackage: require('./TourPackage'),
  Hotel: require('./Hotel'),
  Flight: require('./Flight'),
  Transportation: require('./Transportation'),
  Activity: require('./Activity'),
  Booking: require('./Booking'),
  Payment: require('./Payment'),
  BookingHotel: require('./BookingHotel'),
  BookingFlight: require('./BookingFlight'),
  BookingTransport: require('./BookingTransport'),
  BookingActivity: require('./BookingActivity'),
  Promotion: require('./Promotion'),
  BookingCoupon: require('./BookingCoupon'),
  Review: require('./Review'),
  Favorite: require('./Favorite'),
  CustomizedTour: require('./CustomizedTour'),
};
